# Generated by Django 5.0.6 on 2024-06-06 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('carritoid', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoriaid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedidoid', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('metodo_de_pago', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('observaciones', models.CharField(max_length=285)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('productoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarioid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('contrasenia', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pagoid', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('monto', models.FloatField()),
                ('pedidoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.pedido')),
                ('usuarioid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('inventarioid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_actual', models.IntegerField()),
                ('cantidad_minima', models.IntegerField()),
                ('fecha_ultima_actualizacion', models.DateField(auto_now_add=True)),
                ('productoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('detalle_pedidoid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('pedidoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.pedido')),
                ('productoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('detalle_carritoid', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.carrito')),
                ('productoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='productoid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.producto'),
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('subcategoriaid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=255)),
                ('categoriaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoriaid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.subcategoria'),
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('transaccionesid', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('fecha_y_hora', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=45)),
                ('metodo_pago', models.CharField(max_length=45)),
                ('pagoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.pago')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuarioid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.usuario'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuarioid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.usuario'),
        ),
    ]
