# Generated by Django 5.0.6 on 2024-06-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_usuario_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
